_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
acc_it:
    value: 32
anomaly_ratio:
    value: 1
batch_size:
    value: 32
checkpoints:
    value: ./checkpoints/
clip_grad:
    value: 100
d_model:
    value: 128
data:
    value: All
debug:
    value: online
des:
    value: Exp
dist_url:
    value: env://
dropout:
    value: 0.1
e_layers:
    value: 3
features:
    value: M
fix_seed:
    value: null
freq:
    value: h
inverse:
    value: false
is_training:
    value: 1
itr:
    value: 1
large_model:
    value: true
layer_decay:
    value: null
learning_rate:
    value: 0.003
local_rank:
    value: null
lradj:
    value: prompt_tuning
mask_rate:
    value: 0.25
max_offset:
    value: 0
memory_check:
    value: true
min_lr:
    value: null
model:
    value: UniTS
model_id:
    value: UniTS_pretrain_x128
n_heads:
    value: 8
num_workers:
    value: 0
offset:
    value: 0
patch_len:
    value: 16
pretrained_weight:
    value: auto
project_name:
    value: prompt_tuning
prompt_num:
    value: 10
prompt_tune_epoch:
    value: 2
share_embedding:
    value: false
stride:
    value: 16
subsample_pct:
    value: null
target:
    value: OT
task_data_config_path:
    value: data_provider/multi_task.yaml
task_name:
    value: ALL_task
train_epochs:
    value: 0
warmup_epochs:
    value: 0
weight_decay:
    value: 0
zero_shot_forecasting_new_length:
    value: null
